feat: add sudo for symbolic links

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -20,7 +20,14 @@ download_gpg_key() {
         echo "Downloading GPG key from $url..."
         curl -fsSL "$url" | sudo gpg --dearmor -o "$output_path"
         check_exit_status
-        echo "GPG key saved to $output_path."
+
+        # Verificar si la clave se descargó correctamente
+        if [[ -f "$output_path" ]]; then
+            echo "GPG key saved to $output_path."
+        else
+            echo "Error: GPG key could not be saved. Exiting."
+            exit 1
+        fi
     fi
 }
 
@@ -245,7 +252,7 @@ create_symlink() {
         echo "A file or directory named $link_name already exists but is not a symlink. Skipping creation."
     else
         echo "Creating symlink $link_name -> $target..."
-        ln -s "$target" "$link_name"
+        sudo ln -s "$target" "$link_name"
         check_exit_status
     fi
 }
@@ -298,19 +305,27 @@ else
 fi
 
 # Sublime Text setup
+# wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/sublimehq-archive.gpg > /dev/null
+# echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
 download_gpg_key_wget "https://download.sublimetext.com/sublimehq-pub.gpg" "/etc/apt/trusted.gpg.d/sublimehq-archive.gpg"
 check_sources_list "/etc/apt/sources.list.d/sublime-text.list" "deb https://download.sublimetext.com/ apt/stable/"
 
 
 # Google Cloud SDK setup
-download_gpg_key "https://packages.cloud.google.com/apt/doc/apt-key.gpg" "/usr/share/keyrings/cloud.google.gpg"
+# curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
+# echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
+download_gpg_key_wget "https://packages.cloud.google.com/apt/doc/apt-key.gpg" "/usr/share/keyrings/cloud.google.gpg"
 check_sources_list "/etc/apt/sources.list.d/google-cloud-sdk.list" "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
 
 # Google Chrome setup
+# wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/chrome-keyring.gpg
+# echo "deb [arch=amd64 signed-by=/usr/share/keyrings/chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google.list
 download_gpg_key_wget "https://dl.google.com/linux/linux_signing_key.pub" "/usr/share/keyrings/chrome-keyring.gpg"
 check_sources_list "/etc/apt/sources.list.d/google.list" "deb [arch=amd64 signed-by=/usr/share/keyrings/chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
 
 # Spotify setup
+# curl -sS https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
+# echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
 download_gpg_key "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg" "/etc/apt/trusted.gpg.d/spotify.gpg"
 check_sources_list "/etc/apt/sources.list.d/spotify.list" "deb http://repository.spotify.com stable non-free"
 
